services:
  - type: web
    name: car-project
    runtime: image
    repo: https://github.com/KrasnopevtsevAlexey/your_project
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DB_PATH
        value: /data/cars.db
    healthCheckPath: /healthcheck.php